name: Email in Action
on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step with email 24f1002855@ds.study.iitm.ac.in
        run: echo "Workflow executed successfully"
